server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring: 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/areuareu?serverTimezone=Asia/Seoul
    username: areuareu
    password: bitc5600
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false 
  
file:
<<<<<<< HEAD
  path: C:/Users/admin/Desktop/projectPull/aruerue-back/src/main/resources/static/images/
=======
  path: C:/Users/admin/Desktop/gitclone2/spring-test9/main/resources/static/images/
>>>>>>> ce860e50dee10437888782a68a9eb802f68b97be
